
name: Verify Public GHCR Pull

on:
  workflow_dispatch:
  push:
    branches:
      - feature/lab10

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image without authentication
        run: |
          docker pull ghcr.io/ariiagaf/devops-intro/quicknotes:v0.1.2
          docker image inspect ghcr.io/ariiagaf/devops-intro/quicknotes:v0.1.2
